---
title: "LRBS sample map"
author: "Emma Jones"
date: "8/30/2021"
output: html_document
resource_files:
- config.yml
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

httr::set_config(httr::config(ssl_verifypeer = FALSE, ssl_verifyhost = FALSE))

library(tidyverse)
library(leaflet)
library(leaflet.extras)
library(inlmisc)
#library(config)
library(sf)
library(lubridate)
#library(pool)
library(geojsonsf)
library(pins)
#library(sqldf)
#library(dbplyr)

# Server connection things
conn <- config::get("connectionSettings") # get configuration settings


board_register_rsconnect(key = conn$CONNECT_API_KEY,  #Sys.getenv("CONNECT_API_KEY"),
                         server = conn$CONNECT_SERVER)#Sys.getenv("CONNECT_SERVER"))

assessmentRegions <- st_read( 'data/GIS/AssessmentRegions_simple.shp')
ecoregion <- st_read('data/GIS/vaECOREGIONlevel3__proj84.shp')
subbasins <- st_read('data/GIS/DEQ_VAHUSB_subbasins_EVJ.shp') %>%
  rename('SUBBASIN' = 'SUBBASIN_1') %>%
  mutate(SUBBASIN = ifelse(is.na(SUBBASIN), as.character(BASIN_NAME), as.character(SUBBASIN))) %>%
  mutate(ProbBasin = case_when(SUBBASIN == 'Big Sandy River' ~ 'Big Sandy',
                               SUBBASIN == 'Chowan River' ~ 'Chowan',
                               SUBBASIN %in% c('James River - Lower', "James River - Middle", "James River - Upper") ~ 'James',
                               SUBBASIN == 'New River' ~ 'New',
                               SUBBASIN == 'Potomac River' ~ 'Potomac',
                               SUBBASIN == 'Shenandoah River' ~ 'Shenandoah',
                               SUBBASIN == 'Rappahannock River' ~ 'Rappahannock',
                               SUBBASIN == 'Roanoke River' ~ 'Roanoke',
                               SUBBASIN == 'Clinch and Powell Rivers' ~ 'Clinch',
                               SUBBASIN == 'Holston River' ~ 'Holston',
                               SUBBASIN == 'York River' ~ 'York',
                               TRUE ~ as.character(NA)),
         ProbSuperBasin = case_when(SUBBASIN %in% c('Big Sandy River','Holston River','Clinch and Powell Rivers') ~ 'Tennessee',
                                    SUBBASIN %in% c('Potomac River', 'Shenandoah River') ~ 'Potomac-Shenandoah',
                                    SUBBASIN %in% c('Rappahannock River', 'York River') ~ 'Rappahannock-York',
                                    TRUE ~ as.character(NA)))


LRBS <- pin_get('ejones/LRBS', board = 'rsconnect')
stations <- pin_get('ejones/WQM-Stations-Spatial', board = 'rsconnect')

LRBSstationsSummary <- left_join(LRBS, stations, by = 'StationID') %>% 
  group_by(StationID) %>% 
  mutate(n = n(),
         `Years Sampled` = paste0(year(Date),collapse = ' | ')) %>% 
  filter(! is.na(Latitude) | ! is.na(Longitude)) %>% 
  st_as_sf(coords = c("Longitude", "Latitude"),  # make spatial layer using these columns
           remove = F, # don't remove these lat/lon cols from df
           crs = 4326)

missingMetadata <- left_join(LRBS, stations, by = 'StationID') %>% 
  group_by(StationID) %>% 
  mutate(n = n(),
         `Years Sampled` = paste0(year(Date),collapse = ' | ')) %>% 
  filter(is.na(Latitude) | is.na(Longitude)) 
```

The below map displays all `r nrow(LRBSstationsSummary)` LRBS samples available on the server that have appropriate StationID metadata. There are currently `r nrow(missingMetadata)` samples that do not have appropriate metadata and cannot be displayed. These stations are under review.

```{r map, message=FALSE, warning=FALSE}
# color palette for assessment polygons
pal <- colorFactor(
  palette = topo.colors(7),
  domain = assessmentRegions$ASSESS_REG)
pal2 <- colorFactor(
  palette = rainbow(7),
  domain = ecoregion$US_L3NAME)


CreateWebMap(maps = c("Topo","Imagery","Hydrography"), collapsed = TRUE,
             options= leafletOptions(zoomControl = TRUE,minZoom = 3, maxZoom = 20,
                                     preferCanvas = TRUE)) %>%
  setView(-79.1, 37.7, zoom=7)  %>%
  addPolygons(data= subbasins,  color = 'black', weight = 1,
              fillColor= 'gray', fillOpacity = 0.5,stroke=0.1,
              group="Subbasins", label = ~SUBBASIN) %>% hideGroup("Subbasins") %>%
  addPolygons(data= ecoregion,  color = 'gray', weight = 1,
              fillColor= ~pal2(ecoregion$US_L3NAME), fillOpacity = 0.5,stroke=0.1,
              group="Level III Ecoregions",label = ~US_L3NAME) %>% hideGroup('Level III Ecoregions') %>%
  addPolygons(data= assessmentRegions,  color = 'black', weight = 1,
              fillColor= ~pal(assessmentRegions$ASSESS_REG), fillOpacity = 0.5,stroke=0.1,
              group="Assessment Regions", label = ~ASSESS_REG) %>% hideGroup('Assessment Regions') %>%
  addCircleMarkers(data = LRBSstationsSummary,
                   color='blue', fillColor='yellow', radius = 4,
                   fillOpacity = 0.5,opacity=0.8,weight = 2,stroke=T, group="Stations With LRBS Data",
                   label = ~StationID, layerId = ~StationID,
                   popup = leafpop::popupTable(LRBSstationsSummary, zcol=c('StationID', "n", "Years Sampled"))) %>%
   inlmisc::AddHomeButton(raster::extent(-83.89, -74.80, 36.54, 39.98), position = "topleft") %>%
  addLayersControl(baseGroups=c("Topo","Imagery","Hydrography"),
                   overlayGroups = c("Stations With LRBS Data","Subbasins", "Level III Ecoregions", 'Assessment Regions'),
                   options=layersControlOptions(collapsed=T),
                   position='topleft')
```

Please use the <b><a href='https://rconnect.deq.virginia.gov/CEDSWQMDataQueryTool/' target= '_blank'>CEDS WQM Data Query Tool</a></b> to investigate the LRBS data further.